name: Deploy Terraform NPE  
on:
  pull_request:
    branches:
      - main
      - dev
      - beta
permissions:
  contents: write
  id-token: write
  pull-requests: write
jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BUCKET_NAME: ${{ secrets.RESUME_BUCKET }}
      S3_PREFIX: prod

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: terraform init
        working-directory: ./terraform
        run: terraform init -reconfigure

      - name: terraform plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: terraform apply
        working-directory: ./terraform
        run: |
          terraform apply "tfplan" -auto-approve

      - name: post-deploy actions
        if: github.ref == 'refs/heads/beta'
        run: |
          python terraform/scripts/generate_and_deploy.py \
            --env beta \
            --bucket ${{ env.BUCKET_NAME }} \
            --region ${{ env.AWS_REGION }}
          
